server:
  port: 8090

spring:
  application:
    name: car-service
  jpa:
    open-in-view: false

security:
  auth:
    tokenSecret: secret
    tokenExpirationMsec: 86400000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka