server:
  port: 8081
  error:
    include-message: always # only for dev systems

security:
  auth:
    tokenSecret: secret
    tokenExpirationMsec: 86400000

spring:
  application:
    name: auth-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka