server:
  port: 8080

spring:
  application:
    name: api-gateway

zuul:
  sensitive-headers: Cookie,Set-Cookie
  routes:
    car-service:
      path: /car
      serviceId: car-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

feign:
  hystrix:
    enabled: true